### PR TITLE
Fix for @testID tag handling in Scenario Outline (issue #215)

### LINKED ISSUE #215: Can't define @testID for Scenario Outline examples
**Describe the bug**
Can't assign @testID for Scenario Outline examples (Gherkin features)

**Expected behavior**
Ability to assign allureID to every example in Scenario Outline. 

**Environment**
- Cypress version:                                10.11.0
- cypress-allure-plugin:                         2.40.0
- OS:                                                     Windows 

**Additional context**
In cypress-allure-plugin-example project I see [this Scenario Outline example](https://github.com/Shelex/cypress-allure-plugin-example/blob/master/cypress/e2e/cucumber/examples.feature#L41 ). Unfortunately it has tms link only. When I try this - it works fine, I mean adds link to the Test Case in Test Ops. 

But is there any way to assign allureID (@testID) for Scenario Outline examples?

### PR DESCRIPTION
**Pull request by GalyRain**
This PR fixes the issue with handling `@testID("111|222")` in `Scenario Outline`.

✅ Features:
- Correctly resolves the `AS_ID` per example row
- Keeps compatibility with old and new Gherkin document formats
- Minimal changes to the original codebase
- Retains all original comments and structure

Fixes: #215

### CODE REVIEW

File: reporter/allure-cypress/CucumberHandler.js [hunk 1]
```diff
@@ -224,25 +224,29 @@ class CucumberHandler {
...
-                                    command === 'testID' ? 'AS_ID' : command,
-                                    value
-                                );
+                                // use label name
+                                currentTest.addLabel(command, value);
                             }
                         }
                         return !match;
-                    })
+                    }.bind(this)) // <- bind контекста для this.outlineExampleIndex
```
Comment (Shelex) [inline reporter/allure-cypress/CucumberHandler.js:249]: please change cyrillic comment to english.

**Review by Shelex — COMMENTED** [review]
Hi @GalyRain, thank you for your contribution!

I am completely fine with implementation details, just have one minor yet important comment.

File: reporter/allure-cypress/CucumberHandler.js (hunk 1 above)
Comment (GalyRain) [reply reporter/allure-cypress/CucumberHandler.js]: done 🌹
